### ISSUE TITLE
Question for AutoMAML in Algorithm3 of the paper

### ISSUE THREAD

**Issue by AlbertiPot** [dongzelian/T-NAS#8]
Hi, thanks for your inspiring work

I have one question about the automl algorithm in the appendix: 

while in meta train, there are two repeat inner weights update procedures. Do these two update procedures sever different purposes: the first one for outer weights $\widetilde{w} $ update and the second one for outer architecture $\theta$ update. That is to say, the first step from M for the second inner weight update starts at the finishing of the first outer weight  $\widetilde{w} $ update, i.e. $\widetilde{w} = w^{m}_i$(m is the beginning in the second inner weight update)

**Comment by AlbertiPot** [comment]
Hi, one more question, at the end of section 4, when you obtain the task-specific architecture $\theta_i$, you evaluate it by "training is in the task $T_i$ from the scratch". However, in section 5.2.2， you train the task-specific architecture $\theta_i$ on 15000 tasks. Is that task-specific architecture only for task $T_i$, why do you train it with other tasks?
many thanks

**Comment by dongzelian** [comment]
@AlbertiPot Sorry for the delay. 

1) about the first question, yes. $\theta$ and $w$ are trained alternately. When training $\theta$, $\widetilde{w}$ has been updated. You can check https://github.com/dongzelian/T-NAS/blob/0cc9148dd6e394fc0b9d397b5c9bc8ad8db5a196/auto_maml.py#L172 and https://github.com/dongzelian/T-NAS/blob/0cc9148dd6e394fc0b9d397b5c9bc8ad8db5a196/auto_maml.py#L175

2) for the second question, $\theta_i$ is the task-specific architecture. However, in the few-shot setting, training this task-specific architecture is not easy because this task might only contain 5 images.  Thus, it needs meta learning training procedure. 15000 tasks do not cause image and label leakage, where other tasks (without $T_i$) are trained, and $T_i$ only are added for $w$ update at the meta-test stage.

**Comment by AlbertiPot** [comment]
Many thanks for your detailed answers
best regards
